# Generated by Django 4.2.7 on 2024-03-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_product_id_ingredients_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
