# Generated by Django 4.2.7 on 2024-03-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_skinsolarneeds_skinneeds"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Soap"),
                    (2, "Syndet"),
                    (3, "Bath Gel"),
                    (4, "Bath cream"),
                    (5, "Shampoo"),
                    (6, "Oil"),
                    (7, "Lotion"),
                    (8, "Cream"),
                    (9, "Balm"),
                    (10, "Waters"),
                    (11, "Micellar Water"),
                    (12, "Water Essences"),
                    (13, "Face Mist"),
                    (14, "Mask"),
                    (15, "Sérum"),
                    (16, "Others"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
