# Generated by Django 4.2.7 on 2024-03-18 11:50

import aquaevitae_api.storage
from django.db import migrations, models
import products.models.product


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=aquaevitae_api.storage.OverwriteStorage(),
                upload_to=products.models.product.upload_to,
            ),
        ),
    ]
