# Generated by Django 4.2.7 on 2024-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Soap"),
                    (2, "Syndet"),
                    (3, "Bath Gel"),
                    (4, "Bath cream"),
                    (5, "Shampoo"),
                    (6, "Oil"),
                    (7, "Lotion"),
                    (8, "Cream"),
                    (9, "Balm"),
                    (10, "Waters"),
                    (11, "Micellar Water"),
                    (12, "Water Essences"),
                    (13, "Face Mist"),
                    (14, "Mask"),
                    (15, "Sérum"),
                    (0, "Others"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="skinneeds",
            name="skin_need",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Clean"),
                    (2, "Makeup Remover"),
                    (3, "Hidrate"),
                    (4, "Nourish"),
                    (5, "Soothe"),
                    (6, "Complexion Care"),
                    (7, "Repairers"),
                    (8, "Exfoliating"),
                    (9, "Aging"),
                    (10, "Acne"),
                    (11, "Marks"),
                    (12, "Irritation"),
                    (13, "Antiperspirant"),
                    (14, "Scalp"),
                    (15, "Intimate Care"),
                    (16, "Hands"),
                    (17, "Feet"),
                    (0, "Others"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="skinsolarneeds",
            name="skin_solar_need",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Body Protection"),
                    (2, "Hair Protection"),
                    (3, "Face Protection"),
                    (4, "Aftersun"),
                    (5, "Suntun"),
                    (0, "Others"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="skintype",
            name="skin_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Dry"),
                    (2, "Sensitive"),
                    (3, "Sensible"),
                    (4, "Extra Dry"),
                    (5, "Combined"),
                    (6, "Irritated"),
                    (7, "Normal"),
                    (8, "Normal Dry"),
                    (9, "Normal Combined"),
                    (10, "Atopic Tendency"),
                    (11, "Fragile Damaged"),
                    (0, "All"),
                ],
            ),
        ),
    ]
