# Generated by Django 4.2.7 on 2024-03-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0007_partnershiprequest_remove_partnership_company_and_more"),
        ("products", "0008_alter_product_type_alter_skinneeds_skin_need_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredients",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2001-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredients",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="skinneeds",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2001-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skinneeds",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="skinsolarneeds",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2001-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skinsolarneeds",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="skintype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2001-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skintype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="assigned_partnership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="partnerships.partnershiprequest",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
