# Generated by Django 4.2.7 on 2024-03-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_alter_company_country_alter_company_phone"),
        ("products", "0009_ingredients_created_at_ingredients_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="assigned_partnership",
        ),
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                default="0b509c2c-bb65-422a-9634-3656fdc42dbb",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="companies.company",
            ),
            preserve_default=False,
        ),
    ]
