# Generated by Django 4.2.7 on 2024-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_remove_product_assigned_partnership_product_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product"},
        ),
    ]
