# Generated by Django 4.2.7 on 2024-03-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.URLField(default="http://127.0.0.1:8000"),
            preserve_default=False,
        ),
    ]
