# Generated by Django 4.2.7 on 2024-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_product_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skintype",
            name="skin_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Dry"),
                    (2, "Sensible"),
                    (3, "Extra Dry"),
                    (4, "Combined"),
                    (5, "Irritated"),
                    (6, "Normal"),
                    (7, "Atopic Tendency"),
                    (8, "Fragile Damaged"),
                    (0, "All"),
                ],
            ),
        ),
    ]
