# Generated by Django 4.2.7 on 2023-11-30 17:17

import aquaevitae_api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrequest",
            name="ingredients",
            field=aquaevitae_api.models.SetField(
                base_field=models.CharField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=16,
            ),
        ),
    ]
