# Generated by Django 4.2.7 on 2023-11-30 17:21

import aquaevitae_api.aquaevitae_api.models.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0002_productrequest_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrequest",
            name="ingredients",
            field=aquaevitae_api.base.SetField(
                base_field=models.CharField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
