# Generated by Django 4.2.7 on 2024-03-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0003_alter_productrequest_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrequest",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productrequest",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
