# Generated by Django 4.2.7 on 2024-03-18 15:39

import aquaevitae_api.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0005_remove_productrequest_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrequest",
            name="skin_types",
            field=aquaevitae_api.models.fields.SetField(
                base_field=models.SmallIntegerField(
                    blank=True,
                    choices=[
                        (1, "Dry"),
                        (2, "Sensitive"),
                        (3, "Sensible"),
                        (4, "Extra Dry"),
                        (5, "Combined"),
                        (6, "Irritated"),
                        (7, "Normal"),
                        (8, "Normal Dry"),
                        (9, "Normal Combined"),
                        (10, "Atopic Tendency"),
                        (11, "Fragile Damaged"),
                        (0, "All"),
                    ],
                ),
                default=list,
                size=12,
            ),
        ),
        migrations.AlterField(
            model_name="productrequest",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Soap"),
                    (2, "Syndet"),
                    (3, "Bath Gel"),
                    (4, "Bath cream"),
                    (5, "Shampoo"),
                    (6, "Oil"),
                    (7, "Lotion"),
                    (8, "Cream"),
                    (9, "Balm"),
                    (10, "Waters"),
                    (11, "Micellar Water"),
                    (12, "Water Essences"),
                    (13, "Face Mist"),
                    (14, "Mask"),
                    (15, "Sérum"),
                    (0, "Others"),
                ]
            ),
        ),
    ]
