# Generated by Django 4.2.7 on 2024-03-18 18:11

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0006_alter_productrequest_skin_types_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnershipRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(blank=True, default=False)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Approved"), ("W", "Waiting"), ("D", "Denied")],
                        max_length=1,
                    ),
                ),
                ("company_name", models.CharField(max_length=100, unique=True)),
                ("agent_fullname", models.CharField(max_length=30)),
                ("agent_role", models.CharField(max_length=30, null=True)),
                ("agent_email", models.EmailField(max_length=100, unique=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region=None, unique=True
                    ),
                ),
                ("country", models.CharField(max_length=30, unique=True)),
                ("message", models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name="partnership",
            name="company",
        ),
        migrations.RemoveField(
            model_name="partnership",
            name="company_request",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="partnership",
        ),
        migrations.DeleteModel(
            name="CompanyRequest",
        ),
    ]
