# Generated by Django 4.2.7 on 2024-03-18 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_ingredients_created_at_ingredients_updated_at_and_more"),
        ("companies", "0003_alter_company_assigned_partnership_and_more"),
        ("partnerships", "0007_partnershiprequest_remove_partnership_company_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Partnership",
        ),
        migrations.DeleteModel(
            name="ProductRequest",
        ),
    ]
