# Generated by Django 4.2.7 on 2024-03-18 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0008_delete_partnership_delete_productrequest"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="partnershiprequest",
            table="partnership",
        ),
    ]
