# Generated by Django 4.2.7 on 2024-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0009_alter_partnershiprequest_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnershiprequest",
            name="company_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="partnershiprequest",
            name="country",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name="partnershiprequest",
            unique_together={("company_name", "country")},
        ),
    ]
