# Generated by Django 4.2.7 on 2024-03-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0012_alter_partnershiprequest_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnershiprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Approved"),
                    ("W", "Waiting"),
                    ("D", "Denied"),
                    ("S", "Denied by Server"),
                ],
                default="W",
                max_length=1,
            ),
        ),
    ]
