# Generated by Django 4.2.7 on 2024-03-19 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0013_alter_partnershiprequest_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="partnershiprequest",
            old_name="message",
            new_name="agent_message",
        ),
    ]
