# Generated by Django 4.2.7 on 2024-03-07 15:24

import aquaevitae_api.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "skin_type",
                    aquaevitae_api.models.fields.SetField(
                        base_field=models.SmallIntegerField(
                            choices=[
                                ("<enum.auto object at 0x7f193a7f86a0>", "Dry"),
                                ("<enum.auto object at 0x7f193a7f8550>", "Sensitive"),
                                ("<enum.auto object at 0x7f193a7f8730>", "Sensible"),
                                ("<enum.auto object at 0x7f193a7f87c0>", "Extra Dry"),
                                ("<enum.auto object at 0x7f193a7f8850>", "Combined"),
                                ("<enum.auto object at 0x7f193a7f88e0>", "Irritated"),
                                ("<enum.auto object at 0x7f193a7f8970>", "Normal"),
                                (
                                    "<enum.auto object at 0x7f193a7f8a00>",
                                    "Atopic Tendency",
                                ),
                                (
                                    "<enum.auto object at 0x7f193a7f8ac0>",
                                    "Fragile Damaged",
                                ),
                                ("-1", "All"),
                            ]
                        ),
                        default=list,
                        size=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
