# Generated by Django 4.2.7 on 2024-03-07 15:24

import aquaevitae_api.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="skin_type",
            field=aquaevitae_api.models.fields.SetField(
                base_field=models.SmallIntegerField(
                    choices=[
                        ("<enum.auto object at 0x7ff1773086a0>", "Dry"),
                        ("<enum.auto object at 0x7ff177308550>", "Sensitive"),
                        ("<enum.auto object at 0x7ff177308730>", "Sensible"),
                        ("<enum.auto object at 0x7ff1773087c0>", "Extra Dry"),
                        ("<enum.auto object at 0x7ff177308850>", "Combined"),
                        ("<enum.auto object at 0x7ff1773088e0>", "Irritated"),
                        ("<enum.auto object at 0x7ff177308970>", "Normal"),
                        ("<enum.auto object at 0x7ff177308a00>", "Atopic Tendency"),
                        ("<enum.auto object at 0x7ff177308ac0>", "Fragile Damaged"),
                        ("-1", "All"),
                    ]
                ),
                default=list,
                size=10,
            ),
        ),
    ]
