# Generated by Django 4.2.7 on 2024-03-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0003_alter_form_skin_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="skin_type",
        ),
        migrations.CreateModel(
            name="FormSkinType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skin_type",
                    models.SmallIntegerField(
                        choices=[
                            ("<enum.auto object at 0x7fed88bfc970>", "Dry"),
                            ("<enum.auto object at 0x7fed88bfc610>", "Sensitive"),
                            ("<enum.auto object at 0x7fed88bfcd00>", "Sensible"),
                            ("<enum.auto object at 0x7fed88bfcd90>", "Extra Dry"),
                            ("<enum.auto object at 0x7fed88bfce20>", "Combined"),
                            ("<enum.auto object at 0x7fed88bfd4b0>", "Irritated"),
                            ("<enum.auto object at 0x7fed88bfd540>", "Normal"),
                            ("<enum.auto object at 0x7fed88bfd5d0>", "Atopic Tendency"),
                            ("<enum.auto object at 0x7fed88bfd690>", "Fragile Damaged"),
                            ("-1", "All"),
                        ],
                        default="-1",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skin_types",
                        to="recommendations.form",
                    ),
                ),
            ],
            options={
                "unique_together": {("form", "skin_type")},
            },
        ),
    ]
