# Generated by Django 4.2.7 on 2024-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0004_remove_form_skin_type_formskintype"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="facial_analyze",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formskintype",
            name="skin_type",
            field=models.SmallIntegerField(
                choices=[
                    ("<enum.auto object at 0x7f4021b00970>", "Dry"),
                    ("<enum.auto object at 0x7f4021b00610>", "Sensitive"),
                    ("<enum.auto object at 0x7f4021b00d00>", "Sensible"),
                    ("<enum.auto object at 0x7f4021b00d90>", "Extra Dry"),
                    ("<enum.auto object at 0x7f4021b00e20>", "Combined"),
                    ("<enum.auto object at 0x7f4021b014b0>", "Irritated"),
                    ("<enum.auto object at 0x7f4021b01540>", "Normal"),
                    ("<enum.auto object at 0x7f4021b015d0>", "Atopic Tendency"),
                    ("<enum.auto object at 0x7f4021b01690>", "Fragile Damaged"),
                    ("-1", "All"),
                ],
                default="-1",
            ),
        ),
    ]
