# Generated by Django 4.2.7 on 2024-03-07 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0006_alter_formskintype_skin_type_formskindisease"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="informed_age",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="form",
            name="perceived_age",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="form",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="formskindisease",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formskindisease",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="formskintype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formskintype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="formskindisease",
            name="skin_disease",
            field=models.SmallIntegerField(
                choices=[
                    ("1", "Translucency"),
                    ("2", "Eye Area"),
                    ("3", "Uniformness"),
                    ("4", "Redness"),
                    ("5", "Sagging"),
                    ("6", "Wrinkles"),
                    ("7", "Acne"),
                    ("8", "Hydration"),
                    ("9", "Pigmentation"),
                    ("10", "Blackhead"),
                    ("11", "Pores"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="formskintype",
            name="skin_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Dry"),
                    (2, "Sensitive"),
                    (3, "Sensible"),
                    (4, "Extra Dry"),
                    (5, "Combined"),
                    (6, "Irritated"),
                    (7, "Normal"),
                    (8, "Atopic Tendency"),
                    (9, "Fragile Damaged"),
                    (-1, "NOT_SURE"),
                ],
                default=-1,
            ),
        ),
    ]
