# Generated by Django 4.2.7 on 2024-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0009_alter_form_facial_analyze"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="user_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
