# Generated by Django 4.2.7 on 2024-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0010_form_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="formskindisease",
            name="level",
            field=models.SmallIntegerField(
                choices=[(0, "Translucency"), (1, "Low"), (2, "Medium"), (3, "High")],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formskintype",
            name="skin_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Dry"),
                    (2, "Sensitive"),
                    (3, "Sensible"),
                    (4, "Extra Dry"),
                    (5, "Combined"),
                    (6, "Irritated"),
                    (7, "Normal"),
                    (8, "Atopic Tendency"),
                    (9, "Fragile Damaged"),
                    (0, "Not Sure"),
                ],
                default=0,
            ),
        ),
    ]
