# Generated by Django 4.2.7 on 2024-04-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_alter_facialanalysis_image"),
        ("recommendations", "0013_alter_form_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="facial_analyze",
        ),
        migrations.RemoveField(
            model_name="form",
            name="perceived_age",
        ),
        migrations.AddField(
            model_name="form",
            name="facial_analyzis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="analysis.facialanalysis",
            ),
        ),
        migrations.AlterField(
            model_name="formskintype",
            name="skin_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Dry"),
                    (2, "Sensible"),
                    (3, "Extra Dry"),
                    (4, "Combined"),
                    (5, "Irritated"),
                    (6, "Normal"),
                    (7, "Atopic Tendency"),
                    (8, "Fragile Damaged"),
                    (0, "Not Sure"),
                ],
                default=0,
            ),
        ),
    ]
