# Generated by Django 4.2.7 on 2024-03-27 14:36

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacialAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(blank=True, default=False)),
                (
                    "image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            "/home/guitonello/tese/aquaevitae/api/aquaevitae_api/analysis/images"
                        ),
                        upload_to="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partnership Request",
                "db_table": "facial_analysis",
            },
        ),
    ]
