# Generated by Django 4.2.7 on 2024-03-27 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FacialAnalysis",
        ),
    ]
