# Generated by Django 4.2.7 on 2024-03-28 18:41

import analysis.models.facial_analysis
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_alter_predictions_prediction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facialanalysis",
            name="image",
            field=models.ImageField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    "/home/guitonello/tese/aquaevitae/api/aquaevitae_api/analysis/images"
                ),
                upload_to=analysis.models.facial_analysis.upload_to,
            ),
        ),
    ]
