# Generated by Django 4.2.7 on 2023-11-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='assigned_partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_company', to='partnerships.partnership', unique=True),
        ),
    ]
