# Generated by Django 4.2.7 on 2024-03-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0007_partnershiprequest_remove_partnership_company_and_more"),
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="assigned_partnership",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_company",
                to="partnerships.partnershiprequest",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
