# Generated by Django 4.2.7 on 2023-11-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0002_initial"),
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="assigned_partnership",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_company",
                to="partnerships.partnership",
            ),
        ),
    ]
