# Generated by Django 4.2.7 on 2024-03-20 15:04

from django.db import migrations
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_alter_company_assigned_partnership_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
