# Generated by Django 4.2.7 on 2024-03-20 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_alter_company_country_alter_company_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
    ]
